name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: oven-sh/setup-bun
      - run: bun install
      - run: bun run typecheck
      - run: bun run lint
      - run: bun run build
